"""add broadcast deliveries

Revision ID: 11fba6c3d5c4
Revises: 7ff97d43439f
Create Date: 2026-03-07 14:47:10.338701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11fba6c3d5c4'
down_revision: Union[str, Sequence[str], None] = '7ff97d43439f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_chat_id', sa.BIGINT(), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('recipient_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('recipient_message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_chat_id', 'source_message_id', 'recipient_telegram_id', name='uq_broadcast_source_recipient')
    )
    op.create_index(op.f('ix_broadcast_deliveries_recipient_message_id'), 'broadcast_deliveries', ['recipient_message_id'], unique=False)
    op.create_index(op.f('ix_broadcast_deliveries_recipient_telegram_id'), 'broadcast_deliveries', ['recipient_telegram_id'], unique=False)
    op.create_index(op.f('ix_broadcast_deliveries_source_chat_id'), 'broadcast_deliveries', ['source_chat_id'], unique=False)
    op.create_index(op.f('ix_broadcast_deliveries_source_message_id'), 'broadcast_deliveries', ['source_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcast_deliveries_source_message_id'), table_name='broadcast_deliveries')
    op.drop_index(op.f('ix_broadcast_deliveries_source_chat_id'), table_name='broadcast_deliveries')
    op.drop_index(op.f('ix_broadcast_deliveries_recipient_telegram_id'), table_name='broadcast_deliveries')
    op.drop_index(op.f('ix_broadcast_deliveries_recipient_message_id'), table_name='broadcast_deliveries')
    op.drop_table('broadcast_deliveries')
    # ### end Alembic commands ###
