"""add visitor telegram avatar url

Revision ID: 9fd94634e3e9
Revises: f6d6937f4391
Create Date: 2026-03-06 00:14:10.619725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd94634e3e9'
down_revision: Union[str, Sequence[str], None] = 'f6d6937f4391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('telegram_avatar_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitors', 'telegram_avatar_url')
    # ### end Alembic commands ###
